
export const acciones = [
    {
      "Simbolo": "AAPL",
      "Nombre": "Apple Inc.",
      "Sector": "Tecnología",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 150.25,
      "CapitalizacionBursatil": 2300000000000,
      "Dividendos": 0.82,
      "RelacionPE": 30.5,
      "RendimientoDividendo": 1.5,
      "VolumenOperaciones": 5000000,
      "Beta": 1.2,
      "FechaEmision": "1980-12-12",
      "IndiceRelacionado": "S&P 500",
      "EstrategiasInversion": ["Compra a largo plazo", "Inversión diversificada"],
      "NoticiasEventos": ["Lanzamiento de nuevo iPhone", "Ganancias trimestrales superan expectativas"],
      "HistoricoPrecios": [145.5, 148.2, 152.0, 149.8, 155.3]
    },
    {
      "Simbolo": "GOOGL",
      "Nombre": "Alphabet Inc.",
      "Sector": "Tecnología",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 2750.75,
      "CapitalizacionBursatil": 1900000000000,
      "Dividendos": 0,
      "RelacionPE": 35.2,
      "RendimientoDividendo": 0,
      "VolumenOperaciones": 2000000,
      "Beta": 1.1,
      "FechaEmision": "2004-08-19",
      "IndiceRelacionado": "S&P 500",
      "EstrategiasInversion": ["Inversión a largo plazo", "Enfoque en innovación"],
      "NoticiasEventos": ["Desarrollo de inteligencia artificial", "Expansión de servicios en la nube"],
      "HistoricoPrecios": [2730.2, 2765.8, 2748.3, 2775.1, 2755.6]
    },
    {
      "Simbolo": "MSFT",
      "Nombre": "Microsoft Corporation",
      "Sector": "Tecnología",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 300.45,
      "CapitalizacionBursatil": 2250000000000,
      "Dividendos": 1.10,
      "RelacionPE": 31.8,
      "RendimientoDividendo": 1.8,
      "VolumenOperaciones": 3000000,
      "Beta": 1.0,
      "FechaEmision": "1986-03-13",
      "IndiceRelacionado": "S&P 500",
      "EstrategiasInversion": ["Inversión a largo plazo", "Enfoque en productos y servicios"],
      "NoticiasEventos": ["Lanzamiento de Windows 11", "Adquisición de empresa de ciberseguridad"],
      "HistoricoPrecios": [298.2, 305.7, 302.8, 299.5, 305.0]
    },
    {
      "Simbolo": "AMZN",
      "Nombre": "Amazon.com Inc.",
      "Sector": "Comercio electrónico",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 3400.60,
      "CapitalizacionBursatil": 1700000000000,
      "Dividendos": 0,
      "RelacionPE": 75.6,
      "RendimientoDividendo": 0,
      "VolumenOperaciones": 1500000,
      "Beta": 0.9,
      "FechaEmision": "1997-05-15",
      "IndiceRelacionado": "NASDAQ 100",
      "EstrategiasInversion": ["Crecimiento a largo plazo", "Diversificación de cartera"],
      "NoticiasEventos": ["Expansión de servicios de transmisión", "Innovaciones en logística"],
      "HistoricoPrecios": [3385.0, 3412.8, 3435.2, 3398.7, 3425.4]
    },
    {
      "Simbolo": "TSLA",
      "Nombre": "Tesla Inc.",
      "Sector": "Automotriz",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 750.90,
      "CapitalizacionBursatil": 800000000000,
      "Dividendos": 0,
      "RelacionPE": 120.3,
      "RendimientoDividendo": 0,
      "VolumenOperaciones": 1200000,
      "Beta": 1.5,
      "FechaEmision": "2010-06-29",
      "IndiceRelacionado": "NASDAQ 100",
      "EstrategiasInversion": ["Inversión en crecimiento", "Alta tolerancia al riesgo"],
      "NoticiasEventos": ["Anuncio de nuevas fábricas", "Lanzamiento de modelos innovadores"],
      "HistoricoPrecios": [745.5, 760.2, 752.8, 765.1, 759.6]
    },
    {
      "Simbolo": "FB",
      "Nombre": "Meta Platforms, Inc.",
      "Sector": "Tecnología",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 330.20,
      "CapitalizacionBursatil": 900000000000,
      "Dividendos": 0,
      "RelacionPE": 24.7,
      "RendimientoDividendo": 0,
      "VolumenOperaciones": 1800000,
      "Beta": 1.3,
      "FechaEmision": "2012-05-18",
      "IndiceRelacionado": "NASDAQ 100",
      "EstrategiasInversion": ["Enfoque en redes sociales", "Innovación en tecnología"],
      "NoticiasEventos": ["Cambios en la plataforma", "Adquisiciones estratégicas"],
      "HistoricoPrecios": [328.5, 335.0, 331.2, 327.8, 333.1]
    },
    {
      "Simbolo": "NFLX",
      "Nombre": "Netflix Inc.",
      "Sector": "Entretenimiento",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 550.80,
      "CapitalizacionBursatil": 230000000000,
      "Dividendos": 0,
      "RelacionPE": 50.2,
      "RendimientoDividendo": 0,
      "VolumenOperaciones": 1000000,
      "Beta": 0.8,
      "FechaEmision": "2002-04-14",
      "IndiceRelacionado": "NASDAQ 100",
      "EstrategiasInversion": ["Enfoque en contenido original", "Expansión global"],
      "NoticiasEventos": ["Estreno de nuevas series", "Crecimiento de suscriptores"],
      "HistoricoPrecios": [545.0, 552.8, 549.2, 555.7, 558.4]
    },
    {
      "Simbolo": "V",
      "Nombre": "Visa Inc.",
      "Sector": "Financiero",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 220.60,
      "CapitalizacionBursatil": 450000000000,
      "Dividendos": 0.50,
      "RelacionPE": 40.5,
      "RendimientoDividendo": 1.0,
      "VolumenOperaciones": 800000,
      "Beta": 0.9,
      "FechaEmision": "2008-03-19",
      "IndiceRelacionado": "S&P 500",
      "EstrategiasInversion": ["Inversión a largo plazo", "Estabilidad financiera"],
      "NoticiasEventos": ["Innovaciones en tecnología financiera", "Expansión de servicios"],
      "HistoricoPrecios": [218.5, 222.0, 224.8, 220.3, 225.1]
    },
    {
      "Simbolo": "GS",
      "Nombre": "The Goldman Sachs Group, Inc.",
      "Sector": "Financiero",
      "Tipo": "Ordinaria",
      "ValorNominal": 0.01,
      "PrecioMercado": 400.75,
      "CapitalizacionBursatil": 150000000000,
      "Dividendos": 1.20,
      "RelacionPE": 28.7,
      "RendimientoDividendo": 1.5,
      "VolumenOperaciones": 700000,
      "Beta": 1.1,
      "FechaEmision": "1999-05-04",
      "IndiceRelacionado": "S&P 500",
      "EstrategiasInversion": ["Inversión en servicios financieros", "Gestión de patrimonio"],
      "NoticiasEventos": ["Resultados financieros trimestrales", "Fusiones y adquisiciones"],
      "HistoricoPrecios": [398.2, 403.7, 400.8, 405.5, 402.0]
    },
];
